# Generated by Django 2.1.7 on 2019-03-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190309_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
