# Generated by Django 2.1.7 on 2019-03-09 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='videoUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='homeformfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='to_address',
        ),
        migrations.AddField(
            model_name='homepage',
            name='thank_you_page_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='HomeFormField',
        ),
        migrations.AddField(
            model_name='video',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.videoUploader'),
        ),
    ]
