# Generated by Django 2.1.7 on 2019-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190310_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='video',
            field=models.FileField(default='blah', upload_to=''),
            preserve_default=False,
        ),
    ]
